# Main workflow.

name: HEX publish

on:
  workflow_dispatch

permissions:
  contents: read

jobs:
  publish:

    name: Publish to hex
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        elixir: ['1.17.3']
        otp: ['27.1.2']

    services:
      postgres:
        image: postgres:15.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: aurora_ctx
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        
    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      id: setup-beam
      uses: erlef/setup-beam@5304e04ea2b355f03681464e683d92e3b2f18451 # v1.18.2
      with:
        elixir-version: ${{ matrix.elixir }} # [Required] Define the Elixir version
        otp-version: ${{ matrix.otp }}     # [Required] Define the Erlang/OTP version

    - name: Restore dependencies cache
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}

    - if: ${{steps.cache-deps.outputs.cache-hit != 'true' }}
      name: Ensure dependencies are installed
      run: |
        mix deps.get

    - name: Run tests
      run: mix test

    - name: Publish to Hex.pm
      run: HEX_API_KEY=${{ secrets.HEX_API_KEY }} mix hex.publish --yes


